env: dev

log:
  level: debug
  format: json
  addSource: true
  timeFormat: "2006-01-02 15:04:05"

app:
  name: templar
  publicUrl: "http://localhost:8080"
  jwt:
    secret: supersecretkey123
    accessTokenDuration: templar
    refreshSecret: superrefreshsecret456
    refreshTokenDuration: 1209600
  vnpay:
    tmnCode: ""
    hashSecret: ""
    returnUrl: "http://localhost:3000/payment/vnpay_return"
  search:
    url: "http://localhost:8000"
    denseWeight: 0.75
    sparseWeight: 0.25
    interactionBatchSize: 1

filestore:
  type: s3 # Options: Local, S3, Cloudinary, Remote
  presignedDefaultTTL: 1800 # in seconds
  s3:
    accessKeyID: ""
    secretAccessKey: ""
    region: ""
    bucket: ""
    cloudfrontUrl: ""

postgres:
  # Option 1: Using connection URL
  # url: postgres://user:password@localhost:5432/mydb?sslmode=disable

  # Option 2: Using separate fields (required if URL is not provided)
  host: localhost
  port: 5432
  username: templar
  password: peaktemplarpassword
  database: templar
  maxConnections: 50
  maxIdleConnections: 10
  maxConnIdleTime: 300
  logQuery: true
  allowNestedTransactions: true

redis:
  host: localhost
  port: "6379"
  password: "peaksehopnexuspassword"
  db: 0
